### ISSUE TITLE
Flaky concurrency spec

### ISSUE THREAD

**Issue by bronzdoc** [rubygems/gemstash#298]
```bash
Failures:                                                                                                                         
  1) gemstash concurrency tests storage works with concurrent reads and writes                                                    
     Failure/Error: File.atomic_write(file, File.dirname(file), &block) 
     Errno::EMFILE:                                              
       Too many open files @ rb_sysopen - /Users/bronzdoc/projects/gemstash/tmp/test_base/.metadata.yml20210630-7333-1ow8yg1
     # ./lib/gemstash/env.rb:127:in `atomic_write'                                                                                
     # ./lib/gemstash/storage.rb:65:in `metadata'                                                                                 
     # ./lib/gemstash/storage.rb:77:in `check_storage_version'                                                                    
     # ./lib/gemstash/storage.rb:29:in `initialize'                                                                               
     # ./lib/gemstash/storage.rb:54:in `new'                                                                                      
     # ./lib/gemstash/storage.rb:54:in `for'
     # ./spec/concurrency_spec.rb:14:in `block in write_thread'
```

**Comment by bronzdoc** [comment]
Was something with my my system, `ulimit` was `256` just increased it and is passing
