### ISSUE TITLE
Net::ReadTimeout on Ruby 3

### ISSUE THREAD

**Issue by mlodzi** [rubygems/gemstash#299]
After upgrading to Ruby 3 on Mac OS Big Sur, with several attempts, even reinstalling rvm from scratch, `gemstash start` works, but server is not responding:
```
DEBUG=true bundle install
Using /Users/me/.rvm/gems/ruby-3.0.1
Running `bundle install` with bundler 2.2.21
Found changes from the lockfile, re-resolving dependencies because the dependencies in your gemfile changed
HTTP GET http://localhost:9292/versions
Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
/Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/protocol.rb:219:in `rbuf_fill'
  /Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/protocol.rb:193:in `readuntil'
  /Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/protocol.rb:203:in `readline'
  /Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
  /Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
  /Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
  /Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
  /Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
  /Users/me/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/net/http.rb:1521:in `request'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:876:in `block in request'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendored_persistent.rb:17:in `block in connection_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:608:in `connection_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendored_persistent.rb:16:in `connection_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:870:in `request'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/downloader.rb:63:in `request'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/downloader.rb:19:in `fetch'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/compact_index.rb:131:in `call'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/compact_index_client/updater.rb:48:in `block in update'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/tmpdir/lib/tmpdir.rb:96:in `metmpdir'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/compact_index_client/updater.rb:29:in `update'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/compact_index_client.rb:98:in `update'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/compact_index_client.rb:85:in `update_and_parse_checksums!'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/compact_index.rb:75:in `available?'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/compact_index.rb:16:in `call'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher.rb:162:in `use_api'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `block in api_fetchers'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `select'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `api_fetchers'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:420:in `block in remote_specs'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/index.rb:9:in `build'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:419:in `remote_specs'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:110:in `specs'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:168:in `index_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:176:in `results_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:114:in `search_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:256:in `block in verify_gemfile_dependencies_are_found!'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:253:in `each'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:253:in `verify_gemfile_dependencies_are_found!'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:50:in `start'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:23:in `resolve'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/definition.rb:287:in `resolve'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/definition.rb:179:in `resolve_remotely!'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/installer.rb:284:in `resolve_if_needed'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/installer.rb:83:in `block in run'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/process_lock.rb:9:in `open'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/process_lock.rb:9:in `lock'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/installer.rb:72:in `run'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/installer.rb:24:in `install'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli/install.rb:60:in `run'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli.rb:259:in `block in install'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/settings.rb:132:in `temporary'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli.rb:258:in `install'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli.rb:30:in `dispatch'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli.rb:24:in `start'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/exe/bundle:49:in `block in <top (required)>'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/exe/bundle:37:in `<top (required)>'
  /Users/me/.rvm/gems/ruby-3.0.1/bin/bundle:23:in `load'
  /Users/me/.rvm/gems/ruby-3.0.1/bin/bundle:23:in `<main>'
  /Users/me/.rvm/gems/ruby-3.0.1/bin/ruby_executable_hooks:22:in `eval'
  /Users/me/.rvm/gems/ruby-3.0.1/bin/ruby_executable_hooks:22:in `<main>'
Bundler::HTTPError: Network error while fetching http://localhost:9292/versions (Net::ReadTimeout)
/Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/downloader.rb:76:in `rescue in request'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/downloader.rb:51:in `request'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/downloader.rb:19:in `fetch'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/compact_index.rb:131:in `call'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/compact_index_client/updater.rb:48:in `block in update'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/tmpdir/lib/tmpdir.rb:96:in `metmpdir'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/compact_index_client/updater.rb:29:in `update'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/compact_index_client.rb:98:in `update'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/compact_index_client.rb:85:in `update_and_parse_checksums!'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/compact_index.rb:75:in `available?'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/compact_index.rb:16:in `call'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher/compact_index.rb:16:in `block in compact_index_request'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/fetcher.rb:162:in `use_api'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `block in api_fetchers'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `select'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:415:in `api_fetchers'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:420:in `block in remote_specs'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/index.rb:9:in `build'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:419:in `remote_specs'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/source/rubygems.rb:110:in `specs'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:168:in `index_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:176:in `results_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:114:in `search_for'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:256:in `block in verify_gemfile_dependencies_are_found!'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:253:in `each'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:253:in `verify_gemfile_dependencies_are_found!'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:50:in `start'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/resolver.rb:23:in `resolve'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/definition.rb:287:in `resolve'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/definition.rb:179:in `resolve_remotely!'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/installer.rb:284:in `resolve_if_needed'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/installer.rb:83:in `block in run'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/process_lock.rb:9:in `open'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/process_lock.rb:9:in `lock'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/installer.rb:72:in `run'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/installer.rb:24:in `install'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli/install.rb:60:in `run'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli.rb:259:in `block in install'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/settings.rb:132:in `temporary'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli.rb:258:in `install'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli.rb:30:in `dispatch'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/cli.rb:24:in `start'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/exe/bundle:49:in `block in <top (required)>'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /Users/me/.rvm/gems/ruby-3.0.1/gems/bundler-2.2.21/exe/bundle:37:in `<top (required)>'
  /Users/me/.rvm/gems/ruby-3.0.1/bin/bundle:23:in `load'
  /Users/me/.rvm/gems/ruby-3.0.1/bin/bundle:23:in `<main>'
  /Users/me/.rvm/gems/ruby-3.0.1/bin/ruby_executable_hooks:22:in `eval'
  /Users/me/.rvm/gems/ruby-3.0.1/bin/ruby_executable_hooks:22:in `<main>'
```

Environment:
```
$ bundler --version
Bundler version 2.2.21
$ gemstash --version
Gemstash version 2.1.0
$ gem --version
3.2.21
$ rvm --version
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

$ cat .bundle/config 
---
BUNDLE_JOBS: "4"
BUNDLE_PATH: "vendor/bundle"
BUNDLE_MIRROR__HTTPS://RUBYGEMS__ORG/: "http://localhost:9292"
BUNDLE_MIRROR__HTTPS://RUBYGEMS__ORG/__FALLBACK_TIMEOUT: "3"

$ cat ~/.bundle/config
---
BUNDLE_MIRROR__HTTPS://RUBYGEMS__ORG/: "http://localhost:9292"
BUNDLE_MIRROR__HTTPS://RUBYGEMS__ORG/__FALLBACK_TIMEOUT/: "3"
BUNDLE_PATH: "vendor/bundle"

$ gem list

*** LOCAL GEMS ***

abbrev (default: 0.1.0)
actioncable (6.1.4)
actionmailbox (6.1.4)
actionmailer (6.1.4)
actionpack (6.1.4)
actiontext (6.1.4)
actionview (6.1.4)
activejob (6.1.4)
activemodel (6.1.4)
activerecord (6.1.4)
activestorage (6.1.4)
activesupport (6.1.4, 5.2.6)
ast (2.4.2)
base64 (default: 0.1.0)
benchmark (default: 0.1.1)
bigdecimal (default: 3.0.0)
builder (3.2.4)
bundler (2.2.21)
bundler-unload (1.0.2)
cgi (default: 0.2.0)
concurrent-ruby (1.1.9)
crass (1.0.6)
csv (default: 3.1.9)
dalli (2.7.11)
date (default: 3.1.0)
dbm (default: 1.1.0)
debug (default: 0.1.0)
delegate (default: 0.2.0)
did_you_mean (default: 1.5.0)
digest (default: 3.0.0)
drb (default: 2.0.4)
english (default: 0.7.1)
erb (default: 2.2.0)
erubi (1.10.0)
etc (default: 1.2.0)
executable-hooks (1.6.1)
faraday (0.17.4)
faraday_middleware (0.14.0)
fcntl (default: 1.0.0)
ffi (1.15.3)
fiddle (default: 1.0.6)
fileutils (default: 1.5.0)
find (default: 0.1.0)
foreman (0.87.2)
forwardable (default: 1.3.2)
gdbm (default: 2.1.0)
gem-wrappers (1.4.0)
gemstash (2.1.0)
getoptlong (default: 0.1.1)
globalid (0.4.2)
haml (5.2.1)
haml_lint (0.37.1)
htmlbeautifier (1.3.1)
i18n (1.8.10)
io-console (default: 0.5.7)
io-nonblock (default: 0.1.0)
io-wait (default: 0.1.0)
ipaddr (default: 1.2.2)
irb (default: 1.3.5)
json (default: 2.5.1)
kwalify (0.7.2)
logger (default: 1.4.3)
loofah (2.10.0)
lru_redux (1.1.0)
mail (2.7.1)
marcel (1.0.1)
matrix (default: 0.3.1)
method_source (1.0.0)
mini_mime (1.1.0)
minitest (5.14.2)
multipart-post (2.1.1)
mustermann (1.1.1)
mutex_m (default: 0.1.1)
net-ftp (default: 0.1.1)
net-http (default: 0.1.1)
net-imap (default: 0.1.1)
net-pop (default: 0.1.1)
net-protocol (default: 0.1.0)
net-smtp (default: 0.2.1)
nio4r (2.5.7)
nkf (default: 0.1.0)
nokogiri (1.11.7 x86_64-darwin)
observer (default: 0.1.1)
open-uri (default: 0.1.0)
open3 (default: 0.1.1)
openssl (default: 2.2.0)
optparse (default: 0.1.0)
ostruct (default: 0.3.1)
parallel (1.20.1)
parser (3.0.1.1)
pathname (default: 0.1.0)
pg (1.2.3)
power_assert (1.2.0)
pp (default: 0.1.0)
prettyprint (default: 0.1.0)
prime (default: 0.1.2)
pstore (default: 0.1.1)
psych (default: 3.3.0)
puma (4.3.8)
racc (default: 1.5.1)
rack (2.2.3)
rack-protection (2.1.0)
rack-test (1.1.0)
rails (6.1.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.3.0)
railties (6.1.4)
rainbow (3.0.0)
rake (13.0.3)
rb-fsevent (0.11.0)
rb-inotify (0.10.1)
rbs (1.0.4)
rdoc (default: 6.3.0)
readline (default: 0.0.2)
readline-ext (default: 0.1.1)
reek (6.0.4)
regexp_parser (2.1.1)
reline (default: 0.2.5)
resolv (default: 0.2.0)
resolv-replace (default: 0.1.0)
rexml (3.2.5)
rinda (default: 0.1.0)
roodi (5.0.0)
rss (0.2.9)
rubocop (1.18.2)
rubocop-ast (1.7.0)
rubocop-rspec (2.4.0)
ruby-beautify (0.97.4)
ruby-progressbar (1.11.0)
ruby2_keywords (0.0.4)
ruby_parser (3.16.0)
rubygems-bundler (1.4.5)
rubygems-update (3.2.21)
rvm (1.11.3.9)
sass (3.7.4)
sass-listen (4.0.0)
scss_lint (0.59.0)
securerandom (default: 0.1.0)
sequel (5.46.0)
server_health_check (1.0.2)
server_health_check-rack (0.1.0)
set (default: 1.0.1)
sexp_processor (4.15.3)
shellwords (default: 0.1.0)
sinatra (2.1.0)
singleton (default: 0.1.1)
sprockets (4.0.2)
sprockets-rails (3.2.2)
sqlite3 (1.4.2)
stringio (default: 3.0.0)
strscan (default: 3.0.0)
sysexits (1.2.0)
syslog (default: 0.1.0)
tempfile (default: 0.1.1)
temple (0.8.2)
test-unit (3.3.7)
thor (1.1.0, 0.20.3)
thread_safe (0.3.6)
tilt (2.0.10)
time (default: 0.1.0)
timeout (default: 0.1.1)
tmpdir (default: 0.1.2)
tracer (default: 0.1.1)
tsort (default: 0.1.0)
typeprof (0.12.0)
tzinfo (2.0.4, 1.2.9)
un (default: 0.1.0)
unicode-display_width (2.0.0)
uri (default: 0.10.1)
weakref (default: 0.1.1)
websocket-driver (0.7.5)
websocket-extensions (0.1.5)
yaml (default: 0.1.1)
yard (0.9.26)
zeitwerk (2.4.2)
zlib (default: 1.1.0)

```

Tried also `bundle install --full-index`, but no luck. When I `gemstash stop`, bundling works normally.

**Comment by mlodzi** [comment]
My Gemfile in a Rails project looks like this:
```
$ cat Gemfile
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'
...
```

**Comment by tmaier** [comment]
I think Ruby 3 support has been added in November 2021. See #312
I also deployed Gemstash with a ruby 3-based docker image and did not see any issues.

Can you please check if your issue still exists?
